[program:talkative_celery]
command=/Users/ujjwal/Desktop/talkative/venv/bin/celery -A talkative_proj.celery_app.apps worker --loglevel=info --queues=celery_talkative_processor
directory=/Users/ujjwal/Desktop/talkative/talkative_proj
autostart=true
autorestart=true
stderr_logfile=/tmp/celery.err.log
stdout_logfile=/tmp/celery.out.log
environment=PYTHONUNBUFFERED=true
